# Site settings
title: 一枚大曲奇
url: "https://vinci7.github.io"
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/shanghai
description: >
  美好而常青的昨天，永远是过去，也永远会再来

# Your information
email: appleqyq@163.com
author: Cookies
avatar: "https://vinci7.github.io/yoshiki.png"
profile: 美好而常青的昨天，永远是过去，也永远会再来
#twitter_username: null
github_username:  vinci7
#weibo_username:  null
instagram_username:  appleqyq


permalink: /article/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap


# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false


# Gitalk settings
comment_gitalk_clientId: 7a84fe0175c259dec7de
comment_gitalk_clientSecret: e40b5fe3956371ede31dc5a87e4d8a21bce75de0
comment_gitalk_repo: vinci7.github.io
github_username: vinci7
  