# Site settings
title: 一枚大曲奇
url: "http://www.qiyuqi.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/shanghai
description: >
  骄傲的男人啊，开始了流浪的旅程。

# Your information
email: appleqyq@163.com
author: Cookies
avatar: "http://7xoc7e.com1.z0.glb.clouddn.com/16-6-27/11984575.jpg"
profile: 骄傲的男人啊，开始了流浪的旅程。
twitter_username: appleqyq
github_username:  vinci7
weibo_username:  sunalsorise

# Comment Service (Disqus or 多说)
# choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: vinchi  # get one: http://duoshuo.com/create-site/

permalink: /article/:title
gems:
 - jekyll-paginate
 - jekyll-gist


# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: redcarpet

kramdown:
  input: GFM
  syntax_highlighter: rouge
