name: Herring Cove
author: Herring Cove
markdown: redcarpet
pygments: true
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

##Make sure to edit the above fields, especially for disqus.

